spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-service:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8082

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

jwt:
  Secret-Key: secret
  Expiration-Time: 86400000
