spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/book-service}
    username: postgres
    password: 123
  jpa:
    database:
      platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-service:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8084

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
