spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/account-service
    username: postgres
    password: 123

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8081

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

