spring:
  application:
    name: eureka-service
  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    instance:
      hostname: localhost
server:
  port: 8761
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
